<?php

/**
 * @file
 * USWDS Layout Builder module.
 */

use Drupal\Core\Render\Element;
use Drupal\Core\Template\Attribute;
use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function uswds_blb_configuration_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // @todo update.
    case 'help.page.uswds_blb_configuration':
      $output = '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Add USWDS Grid support to Layout Builder module.
      currently') . '</p>';
      return $output;

    default:
  }
}

/**
 * Implements hook_theme().
 */
function uswds_blb_configuration_theme($existing, $type, $theme, $path) {
  return [
    'uswds_container_wrapper' => [
      'variables' => [
        'attributes' => [],
        'children' => [],
      ],
    ],
    'uswds_container' => [
      'variables' => [
        'attributes' => [],
        'children' => [],
      ],
    ],
    'uswds_section' => [
      'template' => 'uswds-section',
      'render element' => 'content',
      'base hook' => 'layout',
    ],
    'form_element__bs' => [
      'template' => 'form-element--bs',
      'base hook' => 'form-element',
      'path' => $path . '/templates/form',
    ],
    'fieldset__bs' => [
      'template' => 'fieldset--bs',
      'base hook' => 'fieldset',
      'path' => $path . '/templates/form',
    ],
    'input__bs' => [
      'template' => 'input--bs',
      'base hook' => 'input',
      'path' => $path . '/templates/form',
    ],
    'radios__bs' => [
      'template' => 'radios--bs',
      'base hook' => 'radios',
      'path' => $path . '/templates/form',
    ],
    'uswds_video_background' => [
      'variables' => [
        'video_background_url' => '',
        'attributes' => [],
        'children' => [],
      ],
    ],
    'spacing_preview' => [
      'render element' => 'element',
    ],
    'border_preview' => [
      'render element' => 'element',
    ],
    'shadow_preview' => [
      'render element' => 'element',
    ],
    'details__bs' => [
      'template' => 'details--bs',
      'base hook' => 'fieldset',
      'path' => $path . '/templates',
    ],
  ];
}

/**
 * Implements hook_preprocess_html().
 */
function uswds_blb_configuration_preprocess_html(&$variables) {
  $current_path = \Drupal::service('path.current')->getPath();
  if (preg_match('/node\/\d*\/layout/', $current_path) || preg_match('/display\/\w*\/layout/', $current_path)) {
    $variables['attributes']['class'][] = 'layout-builder-form';
  }

  $logged_in = \Drupal::currentUser()->isAuthenticated();
  if ($logged_in) {
    $variables['attributes']['class'][] = 'user-logged-in';
  }
}

/**
 * Implements hook_preprocess_HOOK().
 */
function uswds_blb_configuration_preprocess_uswds_section(&$variables) {
  foreach (Element::children($variables['content']) as $name) {
    if (!isset($variables['content'][$name]['#attributes'])) {
      $variables['content'][$name]['#attributes'] = [];
    }

    /*
     * This is a workaround for modules that pass array as css class value
     * this results in array of arrays that must be flattened before displaying
     * in twig.
     */
    foreach ($variables['content'][$name]['#attributes'] as $k => $v) {
      if (is_array($v)) {
        $result = [];
        array_walk_recursive($v, function ($elem) use (&$result) {
          if ($elem) {
            $result[] = $elem;
          }
        });
        $variables['content'][$name]['#attributes'][$k] = $result;
      }
    }

    $variables['region_attributes'][$name] = new Attribute($variables['content'][$name]['#attributes']);
  }
}

/**
 * Implements hook_page_attachments_alter().
 */
function uswds_blb_configuration_page_attachments_alter(array &$page) {
  $settings = \Drupal::config('uswds_blb_configuration.style_settings');
  $entity_types = array_keys(\Drupal::entityTypeManager()->getDefinitions());
  $layout_routes = [];

  foreach ($entity_types as $entity_type_id) {
    $layout_routes[] = 'layout_builder.defaults.' . $entity_type_id . '.view';
    $layout_routes[] = 'layout_builder.overrides.' . $entity_type_id . '.view';
    // layout_library module.
    $layout_routes[] = 'layout_builder.layout_library.' . $entity_type_id . '.view';
  }

  $route_match = \Drupal::routeMatch();
  // Attach the libraries only in layout route.
  if (in_array($route_match->getRouteName(), $layout_routes)) {
    // Attach the layout builder form styles.
    $page['#attached']['library'][] = 'uswds_blb_configuration/layout_builder_form_style';
    // Attach the font.
    $page['#attached']['library'][] = 'uswds_blb_configuration/offcanvas-font';

    if ($settings->get('layout_builder_theme') && $settings->get('layout_builder_theme') == 'light') {
      $page['#attached']['library'][] = 'uswds_blb_configuration/theme.light';
    }
    else {
      // Attach the default dark theme.
      $page['#attached']['library'][] = 'uswds_blb_configuration/theme.dark';
    }
  }
}

/**
 * Implements hook_theme_suggestions_alter().
 */
function uswds_blb_configuration_theme_suggestions_alter(array &$suggestions, array $variables, $hook) {
  $parents = $variables['element']['#array_parents'] ?? FALSE;
  $bs_parents = ['ui', 'tab_content', 'appearance', 'layout_settings'];

  // UI/Tab content are expected, and one of appearance or layout settings.
  if ($parents && count(array_intersect($bs_parents, $parents)) >= 3) {
    $suggestions[] = $hook . '__bs';
  }
}

/**
 * Implements hook_library_info_alter().
 */
function uswds_blb_configuration_library_info_alter(&$libraries, $extension) {

  if ($extension == 'uswds_blb_configuration'
    && isset($libraries['plugin.scroll_effects.build'])
    && file_exists(DRUPAL_ROOT . '/libraries/aos/dist/aos.js')) {

    if (isset($libraries['plugin.scroll_effects.build']['dependencies'])
      && ($dependency_key = array_search('aos.remote', $libraries['plugin.scroll_effects.build']['dependencies'])) !== FALSE) {

      unset($libraries['plugin.scroll_effects.build']['dependencies'][$dependency_key]);
      $libraries['plugin.scroll_effects.build']['dependencies'][] = 'uswds_blb_configuration/aos.local';

    }
  }
}
